// Generated by gencpp from file PIR/AddTwoInts.msg
// DO NOT EDIT!


#ifndef PIR_MESSAGE_ADDTWOINTS_H
#define PIR_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <PIR/AddTwoIntsRequest.h>
#include <PIR/AddTwoIntsResponse.h>


namespace PIR
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace PIR


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::PIR::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::PIR::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::PIR::AddTwoInts > {
  static const char* value()
  {
    return "PIR/AddTwoInts";
  }

  static const char* value(const ::PIR::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::PIR::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::PIR::AddTwoInts > 
template<>
struct MD5Sum< ::PIR::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::PIR::AddTwoInts >::value();
  }
  static const char* value(const ::PIR::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::PIR::AddTwoIntsRequest> should match 
// service_traits::DataType< ::PIR::AddTwoInts > 
template<>
struct DataType< ::PIR::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::PIR::AddTwoInts >::value();
  }
  static const char* value(const ::PIR::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::PIR::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::PIR::AddTwoInts > 
template<>
struct MD5Sum< ::PIR::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::PIR::AddTwoInts >::value();
  }
  static const char* value(const ::PIR::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::PIR::AddTwoIntsResponse> should match 
// service_traits::DataType< ::PIR::AddTwoInts > 
template<>
struct DataType< ::PIR::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::PIR::AddTwoInts >::value();
  }
  static const char* value(const ::PIR::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PIR_MESSAGE_ADDTWOINTS_H
